version: '2'

services:
    mysqldb:
      image: mysql:5.6
      container_name: mysqldb
      volumes:
        - mysql:/var/lib/mysql
      environment:
        MYSQL_DATABASE: xanthos
        MYSQL_ROOT_PASSWORD: poneyDesBois
    php:
        build: php7-fpm
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/html/xanthos
            - ./logs/symfony:/var/www/html/xanthos/app/logs
    nginx:
        build: nginx
        ports:
            - 8084:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 8085:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx

volumes:
  mysql:
